// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5Zg9n9VVQm3GpGMqm4vDHh
// Component: leoegzsX4eIE

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import LavenderButton from "../../LavenderButton"; // plasmic-import: MtQHjkr4cOvA/component
import Button from "../../Button"; // plasmic-import: ll3hHBC03oBt/component
import { Video } from "@plasmicpkgs/plasmic-basic-components";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 5Zg9n9VVQm3GpGMqm4vDHh/projectcss
import sty from "./PlasmicRoxyRx.module.css"; // plasmic-import: leoegzsX4eIE/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: W-5X1QmV8pcj/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: fHRKrUX_kYZ3/icon

createPlasmicElementProxy;

export type PlasmicRoxyRx__VariantMembers = {};
export type PlasmicRoxyRx__VariantsArgs = {};
type VariantPropType = keyof PlasmicRoxyRx__VariantsArgs;
export const PlasmicRoxyRx__VariantProps = new Array<VariantPropType>();

export type PlasmicRoxyRx__ArgsType = {};
type ArgPropType = keyof PlasmicRoxyRx__ArgsType;
export const PlasmicRoxyRx__ArgProps = new Array<ArgPropType>();

export type PlasmicRoxyRx__OverridesType = {
  root?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  link?: Flex__<"a"> & Partial<LinkProps>;
  lavenderButton?: Flex__<typeof LavenderButton>;
  patientButton?: Flex__<typeof Button>;
  clinicianButton?: Flex__<typeof LavenderButton>;
  htmlVideo?: Flex__<typeof Video>;
  whyChooseUs2?: Flex__<"section">;
  whyChooseUs?: Flex__<"div">;
  whatOurUserAreSaying?: Flex__<"section">;
  whatOurUserAreSaying2?: Flex__<"div">;
  howItWorks?: Flex__<"section">;
  howItWorks2?: Flex__<"div">;
  group11?: Flex__<"div">;
  frame127?: Flex__<"div">;
  _01?: Flex__<"div">;
  _5?: Flex__<"div">;
  _6?: Flex__<"div">;
  _7?: Flex__<"div">;
  supportingCliniciansInProvidingBetterCare?: Flex__<"section">;
  supportingCliniciansInProvidingBetterCare2?: Flex__<"div">;
  patientButton2?: Flex__<typeof Button>;
  clinicianButton2?: Flex__<typeof LavenderButton>;
  footer?: Flex__<"section">;
  howItWorks4?: Flex__<"div">;
  copyright?: Flex__<"div">;
};

export interface DefaultRoxyRxProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRoxyRx__RenderFunc(props: {
  variants: PlasmicRoxyRx__VariantsArgs;
  args: PlasmicRoxyRx__ArgsType;
  overrides: PlasmicRoxyRx__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            brand={
              <PlasmicLink__
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(projectcss.all, projectcss.a, sty.link)}
                component={Link}
                href={"#"}
                platform={"nextjs"}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___13Lm6)}
                  displayHeight={"40px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={{
                    src: "/plasmic/roxy_landing_page/images/frame70Png.png",
                    fullWidth: 128,
                    fullHeight: 45,
                    aspectRatio: undefined
                  }}
                />
              </PlasmicLink__>
            }
            className={classNames("__wab_instance", sty.navigationBar)}
            closeButton={
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__pYb4)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={"https://static1.plasmic.app/close.svg"}
              />
            }
            itemsGap={8}
            menuItems={
              <LavenderButton
                data-plasmic-name={"lavenderButton"}
                data-plasmic-override={overrides.lavenderButton}
                className={classNames("__wab_instance", sty.lavenderButton)}
                transparent={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__fs3Ta
                  )}
                >
                  {"Contact Us"}
                </div>
              </LavenderButton>
            }
            openButton={
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img___05Nu2)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={"https://static1.plasmic.app/menu.svg"}
              />
            }
            responsiveBreakpoint={768}
          />

          <div className={classNames(projectcss.all, sty.freeBox___65IOi)}>
            <div className={classNames(projectcss.all, sty.freeBox__uvC2C)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__mre6W)}
              >
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__gRnm
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "var(--token-p8loL9s6ave3)" }}
                    >
                      {"Personalized"}
                    </span>
                    <React.Fragment>
                      {"\nHealth Management, Tailored to You."}
                    </React.Fragment>
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___8MBTc
                  )}
                >
                  {
                    "Track your medication, monitor your health, and order prescriptions \u2013 all with one smart assistant.\nAre you a patient or a clinician? Let's get started."
                  }
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__bAUu)}
                >
                  <Button
                    data-plasmic-name={"patientButton"}
                    data-plasmic-override={overrides.patientButton}
                    className={classNames("__wab_instance", sty.patientButton)}
                    link={`/patient-form`}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lzIx
                      )}
                    >
                      {"I'm a Patient"}
                    </div>
                  </Button>
                  <LavenderButton
                    data-plasmic-name={"clinicianButton"}
                    data-plasmic-override={overrides.clinicianButton}
                    className={classNames(
                      "__wab_instance",
                      sty.clinicianButton
                    )}
                  >
                    {"I'm a Clinician"}
                  </LavenderButton>
                </Stack__>
              </Stack__>
              <div className={classNames(projectcss.all, sty.freeBox__rMhF)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__lG5L)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/roxy_landing_page/images/heroImage1Png.png",
                    fullWidth: 606,
                    fullHeight: 587,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </div>
          <section className={classNames(projectcss.all, sty.section__lfXfP)}>
            <section
              className={classNames(projectcss.all, sty.section___63J60)}
            >
              <Video
                data-plasmic-name={"htmlVideo"}
                data-plasmic-override={overrides.htmlVideo}
                className={classNames("__wab_instance", sty.htmlVideo)}
                controls={false}
                loop={true}
                src={
                  "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm"
                }
              />
            </section>
          </section>
          <section
            data-plasmic-name={"whyChooseUs2"}
            data-plasmic-override={overrides.whyChooseUs2}
            className={classNames(projectcss.all, sty.whyChooseUs2)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"whyChooseUs"}
              data-plasmic-override={overrides.whyChooseUs}
              hasGap={true}
              className={classNames(projectcss.all, sty.whyChooseUs)}
            >
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__rceNw
                )}
              >
                {"Why Choose RoxyRX?"}
              </h1>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___0JzUs)}
              >
                <section
                  className={classNames(projectcss.all, sty.section__xEm8R)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___0YC7M)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/roxy_landing_page/images/frame124Png.png",
                      fullWidth: 608,
                      fullHeight: 364,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__kgwrx)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__ykPtp
                      )}
                    >
                      {"AI-Assisted Capture"}
                    </h1>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__joqvY
                      )}
                    >
                      {
                        "Easily scan and upload prescriptions, while AI learns about your health condition."
                      }
                    </div>
                  </div>
                </section>
                <section
                  className={classNames(projectcss.all, sty.section__rjwQ0)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__cw4DH)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/roxy_landing_page/images/frame1241Png.png",
                      fullWidth: 608,
                      fullHeight: 364,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox___50N2)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__kmkZk
                      )}
                    >
                      {"AI-Assisted Capture"}
                    </h1>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ficEm
                      )}
                    >
                      {
                        "Easily scan and upload prescriptions, while AI learns about your health condition."
                      }
                    </div>
                  </div>
                </section>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__bpjCv)}
              >
                <section
                  className={classNames(projectcss.all, sty.section__zUjd)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___7BRk)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/roxy_landing_page/images/frame124Png.png",
                      fullWidth: 608,
                      fullHeight: 364,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__fwzd6)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__pHlAx
                      )}
                    >
                      {"AI-Assisted Capture"}
                    </h1>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eNqZu
                      )}
                    >
                      {
                        "Easily scan and upload prescriptions, while AI learns about your health condition."
                      }
                    </div>
                  </div>
                </section>
                <section
                  className={classNames(projectcss.all, sty.section___5J3)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___8Sdln)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/roxy_landing_page/images/frame1241Png.png",
                      fullWidth: 608,
                      fullHeight: 364,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__e9F9T)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__nyAK
                      )}
                    >
                      {"AI-Assisted Capture"}
                    </h1>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4TV2S
                      )}
                    >
                      {
                        "Easily scan and upload prescriptions, while AI learns about your health condition."
                      }
                    </div>
                  </div>
                </section>
              </Stack__>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"whatOurUserAreSaying"}
            data-plasmic-override={overrides.whatOurUserAreSaying}
            className={classNames(projectcss.all, sty.whatOurUserAreSaying)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"whatOurUserAreSaying2"}
              data-plasmic-override={overrides.whatOurUserAreSaying2}
              hasGap={true}
              className={classNames(projectcss.all, sty.whatOurUserAreSaying2)}
            >
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__vWv7H
                )}
              >
                {"What Our Users Are Saying"}
              </h1>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ybA9U
                )}
              >
                {
                  "Here is some quote which was provided by our satisfied customer"
                }
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__h7Rg)}
              >
                <section
                  className={classNames(projectcss.all, sty.section___7FoqD)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__wlAN
                    )}
                  >
                    {
                      "As someone who is 65 years old and takes over a dozen medicines, Roxy has helped me understand why I'm taking them and when to get help from my GP"
                    }
                  </h1>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___5Pluh)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___3KBtn)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"60px"}
                      loading={"lazy"}
                      src={
                        "https://plus.unsplash.com/premium_photo-1678197937465-bdbc4ed95815?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGVyc29ufGVufDB8fDB8fHww"
                      }
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__kMrgT
                      )}
                    >
                      {"Mohammad Ali."}
                    </div>
                  </Stack__>
                </section>
                <section
                  className={classNames(projectcss.all, sty.section__uic42)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__hQNzq
                    )}
                  >
                    {
                      "Roxy has helped me and my GP identify some unusual symptoms I had been experiencing for a couple of weeks were not because of my medication and because of underlying health condition. This meant that the GP was able to urgently refer me to a specialist to proper treatment "
                    }
                  </h1>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__ibm3)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__iKo9E)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"60px"}
                      loading={"lazy"}
                      src={
                        "https://plus.unsplash.com/premium_photo-1678197937465-bdbc4ed95815?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGVyc29ufGVufDB8fDB8fHww"
                      }
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lmmhu
                      )}
                    >
                      {"Mohammad Ali."}
                    </div>
                  </Stack__>
                </section>
                <section
                  className={classNames(projectcss.all, sty.section__pFcK1)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__zsRd7
                    )}
                  >
                    {
                      "\u201cThis app helped me stay on track with my medication. I\u2019ve never felt more in control of my health!\u201d"
                    }
                  </h1>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__dfcTf)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__mzYpg)}
                      displayHeight={"60px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"60px"}
                      loading={"lazy"}
                      src={
                        "https://plus.unsplash.com/premium_photo-1678197937465-bdbc4ed95815?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGVyc29ufGVufDB8fDB8fHww"
                      }
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sQgzW
                      )}
                    >
                      {"Mohammad Ali."}
                    </div>
                  </Stack__>
                </section>
              </Stack__>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"howItWorks"}
            data-plasmic-override={overrides.howItWorks}
            className={classNames(projectcss.all, sty.howItWorks)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"howItWorks2"}
              data-plasmic-override={overrides.howItWorks2}
              hasGap={true}
              className={classNames(projectcss.all, sty.howItWorks2)}
            >
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__juYfR
                )}
              >
                {"How it works"}
              </h1>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__mbFsk
                )}
              >
                {"Here is a guide about how our product works"}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__k2Yq)}
              >
                <div
                  data-plasmic-name={"group11"}
                  data-plasmic-override={overrides.group11}
                  className={classNames(projectcss.all, sty.group11)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___5JqpK)}
                    displayHeight={"2060px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"6px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/roxy_landing_page/images/line3.svg",
                      fullWidth: 6,
                      fullHeight: 2060,
                      aspectRatio: 0.002913
                    }}
                  />

                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame127"}
                    data-plasmic-override={overrides.frame127}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame127)}
                  >
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"_01"}
                      data-plasmic-override={overrides._01}
                      hasGap={true}
                      className={classNames(projectcss.all, sty._01)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__m8T7R
                        )}
                      >
                        {"01"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"_5"}
                      data-plasmic-override={overrides._5}
                      hasGap={true}
                      className={classNames(projectcss.all, sty._5)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aDXen
                        )}
                      >
                        {"02"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"_6"}
                      data-plasmic-override={overrides._6}
                      hasGap={true}
                      className={classNames(projectcss.all, sty._6)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__swW5K
                        )}
                      >
                        {"03"}
                      </div>
                    </Stack__>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"_7"}
                      data-plasmic-override={overrides._7}
                      hasGap={true}
                      className={classNames(projectcss.all, sty._7)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pyawg
                        )}
                      >
                        {"04"}
                      </div>
                    </Stack__>
                  </Stack__>
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__k0Y5)}
                >
                  <section
                    className={classNames(projectcss.all, sty.section__sPmjy)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__mk8Ge)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/roxy_landing_page/images/frame114Png.png",
                        fullWidth: 701,
                        fullHeight: 297,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__wpbe7)}
                    >
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1__emoXf
                        )}
                      >
                        {"Set Up Your Profile"}
                      </h1>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___94VQc
                        )}
                      >
                        {
                          "Setup your profile using basic information and your health condition details."
                        }
                      </div>
                    </div>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section___39HaJ)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__vAnCv)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/roxy_landing_page/images/frame115Png.png",
                        fullWidth: 701,
                        fullHeight: 297,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5UIng
                      )}
                    >
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1__gpeuC
                        )}
                      >
                        {"No English? No problem!"}
                      </h1>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yAoFw
                        )}
                      >
                        {
                          "Roxy is designed to be an inclusive app which supports people regardless of their ability to read, write or speak English by providing text-based, visual and audio support for users"
                        }
                      </div>
                    </div>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__dtq3W)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__ouok7)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/roxy_landing_page/images/frame116Png.png",
                        fullWidth: 701,
                        fullHeight: 297,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__jh1KY)}
                    >
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1__vxaM
                        )}
                      >
                        {
                          "Personalised insights about your health conditions and medication"
                        }
                      </h1>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lYd3X
                        )}
                      >
                        {
                          "\nPersonalised insights about your health conditions and medication"
                        }
                      </div>
                    </div>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section___0Pjo7)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__vpRd9)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/roxy_landing_page/images/frame117Png.png",
                        fullWidth: 701,
                        fullHeight: 297,
                        aspectRatio: undefined
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__vcFF)}
                    >
                      <h1
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1__vtecm
                        )}
                      >
                        {"Support outside the point of care"}
                      </h1>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__h9Jaf
                        )}
                      >
                        {
                          "have question about health or medicaiton but cannot speak to a health professionals? You can use Roxy to find out basic information and see if you need to call 111 or speak to your Doctor/Pharmacist"
                        }
                      </div>
                    </div>
                  </section>
                </Stack__>
              </Stack__>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"supportingCliniciansInProvidingBetterCare"}
            data-plasmic-override={
              overrides.supportingCliniciansInProvidingBetterCare
            }
            className={classNames(
              projectcss.all,
              sty.supportingCliniciansInProvidingBetterCare
            )}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"supportingCliniciansInProvidingBetterCare2"}
              data-plasmic-override={
                overrides.supportingCliniciansInProvidingBetterCare2
              }
              hasGap={true}
              className={classNames(
                projectcss.all,
                sty.supportingCliniciansInProvidingBetterCare2
              )}
            >
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__m2AT6
                )}
              >
                {"Supporting Clinicians in Providing Better Care"}
              </h1>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__pr088
                )}
              >
                {
                  "RoxyRx helps clinicians manage large patient populations, track medication adherence, and identify key health metrics. Our AI adapts to your patients\u2019 needs"
                }
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__ay7B8)}
              >
                <Button
                  data-plasmic-name={"patientButton2"}
                  data-plasmic-override={overrides.patientButton2}
                  className={classNames("__wab_instance", sty.patientButton2)}
                  link={`/patient-form`}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bnAwy
                    )}
                  >
                    {"I'm a Patient"}
                  </div>
                </Button>
                <LavenderButton
                  data-plasmic-name={"clinicianButton2"}
                  data-plasmic-override={overrides.clinicianButton2}
                  className={classNames("__wab_instance", sty.clinicianButton2)}
                >
                  {"I'm a Clinician"}
                </LavenderButton>
              </Stack__>
            </Stack__>
          </section>
          <section
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"howItWorks4"}
              data-plasmic-override={overrides.howItWorks4}
              hasGap={true}
              className={classNames(projectcss.all, sty.howItWorks4)}
            />
          </section>
          <Stack__
            as={"div"}
            data-plasmic-name={"copyright"}
            data-plasmic-override={overrides.copyright}
            hasGap={true}
            className={classNames(projectcss.all, sty.copyright)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__zKsAe
              )}
            >
              <React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "var(--token-hT_9fWwnelJE)" }}
                >
                  {"\u00a9 2024 RoxyRX"}
                </span>
              </React.Fragment>
            </div>
          </Stack__>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navigationBar",
    "link",
    "lavenderButton",
    "patientButton",
    "clinicianButton",
    "htmlVideo",
    "whyChooseUs2",
    "whyChooseUs",
    "whatOurUserAreSaying",
    "whatOurUserAreSaying2",
    "howItWorks",
    "howItWorks2",
    "group11",
    "frame127",
    "_01",
    "_5",
    "_6",
    "_7",
    "supportingCliniciansInProvidingBetterCare",
    "supportingCliniciansInProvidingBetterCare2",
    "patientButton2",
    "clinicianButton2",
    "footer",
    "howItWorks4",
    "copyright"
  ],
  navigationBar: ["navigationBar", "link", "lavenderButton"],
  link: ["link"],
  lavenderButton: ["lavenderButton"],
  patientButton: ["patientButton"],
  clinicianButton: ["clinicianButton"],
  htmlVideo: ["htmlVideo"],
  whyChooseUs2: ["whyChooseUs2", "whyChooseUs"],
  whyChooseUs: ["whyChooseUs"],
  whatOurUserAreSaying: ["whatOurUserAreSaying", "whatOurUserAreSaying2"],
  whatOurUserAreSaying2: ["whatOurUserAreSaying2"],
  howItWorks: [
    "howItWorks",
    "howItWorks2",
    "group11",
    "frame127",
    "_01",
    "_5",
    "_6",
    "_7"
  ],
  howItWorks2: ["howItWorks2", "group11", "frame127", "_01", "_5", "_6", "_7"],
  group11: ["group11", "frame127", "_01", "_5", "_6", "_7"],
  frame127: ["frame127", "_01", "_5", "_6", "_7"],
  _01: ["_01"],
  _5: ["_5"],
  _6: ["_6"],
  _7: ["_7"],
  supportingCliniciansInProvidingBetterCare: [
    "supportingCliniciansInProvidingBetterCare",
    "supportingCliniciansInProvidingBetterCare2",
    "patientButton2",
    "clinicianButton2"
  ],
  supportingCliniciansInProvidingBetterCare2: [
    "supportingCliniciansInProvidingBetterCare2",
    "patientButton2",
    "clinicianButton2"
  ],
  patientButton2: ["patientButton2"],
  clinicianButton2: ["clinicianButton2"],
  footer: ["footer", "howItWorks4"],
  howItWorks4: ["howItWorks4"],
  copyright: ["copyright"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navigationBar: typeof NavigationBar;
  link: "a";
  lavenderButton: typeof LavenderButton;
  patientButton: typeof Button;
  clinicianButton: typeof LavenderButton;
  htmlVideo: typeof Video;
  whyChooseUs2: "section";
  whyChooseUs: "div";
  whatOurUserAreSaying: "section";
  whatOurUserAreSaying2: "div";
  howItWorks: "section";
  howItWorks2: "div";
  group11: "div";
  frame127: "div";
  _01: "div";
  _5: "div";
  _6: "div";
  _7: "div";
  supportingCliniciansInProvidingBetterCare: "section";
  supportingCliniciansInProvidingBetterCare2: "div";
  patientButton2: typeof Button;
  clinicianButton2: typeof LavenderButton;
  footer: "section";
  howItWorks4: "div";
  copyright: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRoxyRx__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRoxyRx__VariantsArgs;
    args?: PlasmicRoxyRx__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRoxyRx__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicRoxyRx__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRoxyRx__ArgProps,
          internalVariantPropNames: PlasmicRoxyRx__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRoxyRx__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRoxyRx";
  } else {
    func.displayName = `PlasmicRoxyRx.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "5Zg9n9VVQm3GpGMqm4vDHh"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicRoxyRx = Object.assign(
  // Top-level PlasmicRoxyRx renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    link: makeNodeComponent("link"),
    lavenderButton: makeNodeComponent("lavenderButton"),
    patientButton: makeNodeComponent("patientButton"),
    clinicianButton: makeNodeComponent("clinicianButton"),
    htmlVideo: makeNodeComponent("htmlVideo"),
    whyChooseUs2: makeNodeComponent("whyChooseUs2"),
    whyChooseUs: makeNodeComponent("whyChooseUs"),
    whatOurUserAreSaying: makeNodeComponent("whatOurUserAreSaying"),
    whatOurUserAreSaying2: makeNodeComponent("whatOurUserAreSaying2"),
    howItWorks: makeNodeComponent("howItWorks"),
    howItWorks2: makeNodeComponent("howItWorks2"),
    group11: makeNodeComponent("group11"),
    frame127: makeNodeComponent("frame127"),
    _01: makeNodeComponent("_01"),
    _5: makeNodeComponent("_5"),
    _6: makeNodeComponent("_6"),
    _7: makeNodeComponent("_7"),
    supportingCliniciansInProvidingBetterCare: makeNodeComponent(
      "supportingCliniciansInProvidingBetterCare"
    ),
    supportingCliniciansInProvidingBetterCare2: makeNodeComponent(
      "supportingCliniciansInProvidingBetterCare2"
    ),
    patientButton2: makeNodeComponent("patientButton2"),
    clinicianButton2: makeNodeComponent("clinicianButton2"),
    footer: makeNodeComponent("footer"),
    howItWorks4: makeNodeComponent("howItWorks4"),
    copyright: makeNodeComponent("copyright"),

    // Metadata about props expected for PlasmicRoxyRx
    internalVariantProps: PlasmicRoxyRx__VariantProps,
    internalArgProps: PlasmicRoxyRx__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicRoxyRx;
/* prettier-ignore-end */
